### ISSUE TITLE
In Dify , An error was reported after calling the MCP server, then exited.

### ISSUE THREAD

**Issue by qlanto224** [bytebase/dbhub#31]
An error was reported after calling the MCP server.

 mcp server error :
```
Client Message d3d46487-d00f-4d44-a980-d819d8bc4758
file:///app/node_modules/.pnpm/@modelcontextprotocol+sdk@1.6.1/node_modules/@modelcontextprotocol/sdk/dist/esm/server/sse.js:53
            throw new Error(message);
                  ^

Error: SSE connection not established
    at SSEServerTransport.handlePostMessage (file:///app/node_modules/.pnpm/@modelcontextprotocol+sdk@1.6.1/node_modules/@modelcontextprotocol/sdk/dist/esm/server/sse.js:53:19)
    at file:///app/dist/index.js:2732:25
    at Layer.handle [as handle_request] (/app/node_modules/.pnpm/express@4.21.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/.pnpm/express@4.21.2/node_modules/express/lib/router/route.js:149:13)
    at Route.dispatch (/app/node_modules/.pnpm/express@4.21.2/node_modules/express/lib/router/route.js:119:3)
    at Layer.handle [as handle_request] (/app/node_modules/.pnpm/express@4.21.2/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/.pnpm/express@4.21.2/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/.pnpm/express@4.21.2/node_modules/express/lib/router/index.js:346:12)
    at next (/app/node_modules/.pnpm/express@4.21.2/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/app/node_modules/.pnpm/express@4.21.2/node_modules/express/lib/middleware/init.js:40:5)

Node.js v22.14.0

```

**Comment by theboringhumane** [comment]
Which package are you using to connect to the server? For example, are you using Claude, Cursor, or another package?

**Comment by qlanto224** [comment]
> Which package are you using to connect to the server? For example, are you using Claude, Cursor, or another package?

sse

**Comment by qlanto224** [comment]
This is my docker-compose yaml:
```yaml
  pg-mcp:
    image: bytebase/dbhub:0.3.1
    container_name: pg-mcp
    init: true
    ports:
      - "8001:8080"
    command:
      - --transport
      - sse
      - --port
      - "8080"
      - --dsn
      - "postgres://account:pwd@host:5432/mydb?sslmode=disable"
    networks:
      - mcp_net
```
