### ISSUE TITLE
ConnectionError with SQL Server and self-signed certificate, even with trustServerCertificate=true

### ISSUE THREAD

**Issue by michelepangrazi** [bytebase/dbhub#57]
Hi,
I'm trying to use dbhub to connect to a local SQL Server running in a Docker container, but I keep getting a ConnectionError related to a self-signed certificate, even when using trustServerCertificate=true.

🐳 Docker Compose setup
```yaml
version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  dbhub:
    image: bytebase/dbhub
    container_name: dbhub
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    command: >
      --transport http
      --port 8080
      --dsn="sqlserver://sa:YourStrongPassw0rd@sqlserver:1433/master?encrypt=true&trustServerCertificate=true"
    restart: unless-stopped

volumes:
  sql_data:

```

❗ Error log from dbhub:

```text
Connecting with DSN: sqlserver://sa:*******@sqlserver:1433/master?trustServerCertificate
Fatal error: ConnectionError: Failed to connect to sqlserver:1433 - self-signed certificate
...
[cause]: Error: self-signed certificate
  at TLSSocket.onConnectSecure (node:_tls_wrap:1679:34)
  ...
  code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
```
✅ What I expected:
Given encrypt=true&trustServerCertificate=true is present in the DSN, I expected the connection to succeed despite the self-signed certificate.

💡 Notes:
I tested this both using sslmode=disable and encrypt=false, but dbhub always seems to enforce encryption via tedious.
